### ISSUE TITLE
Add documentation for tests, CI checks

### ISSUE THREAD

**Issue by jessieay** [18F/team_api#10]
As a developer in order to do my work, I need to understand how to run the  tests efficiently.

Acceptance criteria: there is documentation somewhere in the repository (in the README) that is easily accessible to developers that contains instructions on how to run tests.

Notes: 
There are specs and linters for this repo but no checks have been added to GitHub. We should run those so people can see the status of the build for a PR/branch and also document how to run tests locally

**Comment by mtorres253** [comment]
There is a travis file but we still have to update the readme

**Comment by jessieay** [comment]
PR integration would be :100: http://blog.travis-ci.com/2012-09-04-pull-requests-just-got-even-more-awesome/
