### ISSUE TITLE
Naming of this GitHub repo is confusing

### ISSUE THREAD

**Issue by jessieay** [18F/team_api#11]
Is there a way we could name this and https://github.com/18F/team-api (private repo) so that their different responsibilities are more obvious? (I don't understand the responsibilities enough to have any good suggestions...but am happy to provide feedback on any ideas that others have)

**Comment by jessieay** [comment]
cc @fureigh

**Comment by fureigh** [comment]
We'll call it a team effort. (Hopefully that joke doesn't make you regret the cc.)

**Comment by fureigh** [comment]
I'm happy to namestorm with whoever better understands the difference between the two projects.

**Comment by gbinal** [comment]
Hmmm. Fair point.    @mbland - any thoughts on making one a bit more distinct?

**Comment by mbland** [comment]
Yeah, the name collision was an unfortunate development. 18F/team_api is where we put all the code that we can share with the public, and 18F/team-api contains the original team/project/etc. data and the https://team-api.18f.gov/ server engine. 18F/team-api imports 18F/team_api as a Jekyll plugin, and also contains the Node server that listens for webhooks and rebuilds the site.

I created 18F/team-api first, and we started putting all the code in there, and then when I cut the gem, I couldn't think of a better repo name at the time. I think the gem's repo name will stay the same, but perhaps we could rename this to team-api-server or some such. (Eventually I'd like to move the remaining parts of `scripts` and the Node server into public repos, but haven't gotten around to it yet.)

Or, in the footsteps of 18F/18f.gsa.gov, maybe 18F/team-api.18f.gov makes sense. Actually, hell, I'm going to just do that now. Done.

**Comment by gbinal** [comment]
Sounds good.  Thanks, @mbland for bringing so much of this together.

**Comment by jessieay** [comment]
@mbland @gbinal @fureigh I like the new name for https://github.com/18F/team-api.18f.gov - nice change!

I still find the name of *this* repo to be unclear. You say "I think the gem's repo name will stay the same" - why is that?

**Comment by mbland** [comment]
Because it matches the name of the gem, as documented on the repo's home page/in the README.
