### ISSUE TITLE
Borked URLs and link text on some "related links"

### ISSUE THREAD

**Issue by jmcarp** [18F/team_api#21]
The URL and link text for C2 on the dashboard are garbled: https://18f.gsa.gov/dashboard/project/C2/

<img width="386" alt="screen shot 2015-10-22 at 3 59 47 pm" src="https://cloud.githubusercontent.com/assets/1633460/10676938/745dabaa-78d7-11e5-8b1e-378cffea2e4e.png">

I didn't notice bad links for other projects, so maybe something's up with the .about.yml file on C2.

cc @mbland @gboone

**Comment by pkarman** [comment]
thanks, already fixed in master but not yet deployed (will deploy in an hour). see also https://github.com/18F/dashboard/issues/273

**Comment by mbland** [comment]
This is fixed now, per 18F/dashboard#273.

Of course, the underlying robustness issues are ongoing.
