### ISSUE TITLE
Automate the import of projects from data-private

### ISSUE THREAD

**Issue by mtorres253** [18F/team_api#41]
In order for 18F to make project information available to the public, we should be able to specify project information for projects without repos, and we should be able to add that information to the data that is returned by Team API.

Right now, this is done manuallly. This story is to automate the import of this data. The logic is currently: anything that exists in both locations will be overwritten by the data in about.yml

- [ ] refactor current script?
- [ ] schedule the job

This is a pairing opportunity

Acceptance criteria: 
I am a project owner of a project that doesn't have its own repo
I add the project to data-private
The Team API does its regular update of project data
I should see my project returned when I go to https://team-api.18f.gov/api/projects/

**Comment by ccostino** [comment]
I am closing this issue in favor of https://github.com/18F/team-api-server/issues/2 since that is the repo where this work is going to actually take place.
