### ISSUE TITLE
Produce /schemas endpoint

### ISSUE THREAD

**Issue by mbland** [18F/team_api#44]
So that developers can easily have access to the schema, for validation and such, we should give them a way to easily access the current schema via an api endpoint.

We should post one `/schemas` sub-endpoint for each of the top-level endpoints (`/team`, `/projects`, `/working-groups`, etc.)

cc: @jeremiak

**Comment by mbland** [comment]
Would like to prioritize this per @ultrasaurus's comments in today's Dashboard sprint meeting.

**Comment by mtorres253** [comment]
This is just an endpoint for about.yml schema that other tools can use.
