### ISSUE TITLE
Downcase all filenames

### ISSUE THREAD

**Issue by ertzeid** [18F/team_api#48]
Due to the way Git and OS X handle capitalization in filenames, problems can arise when renaming a file in a way that only changes capitalization. To avoid problems in the future, we should make all of our project/team/etc. import filenames be all lowercase by default.

Acceptance criteria:
- [ ] All files in `_projects` and other relevant directories have lowercase names
- [ ] Files created from importing `.about.yml` files have lowercase names

To avoid as many problems as possible from automatically renaming files through the import, we should force-rename the files through git ahead of time, so the procedure should go something like this:
- [ ] Change any filenames that are not already lowercase to all-lowercase with a `git mv -f [FileName] [filename]`
- [ ] Update the import code to do this by default

**Comment by mbland** [comment]
Note that there's a git config variable, [`core.ignorecase`](https://www.kernel.org/pub/software/scm/git/docs/git-config.html), that might come into play. It's automatically set by `git clone` based on the host file system. It needs to be false for git to perform the `FileName` to `filename` conversion.

Ping me to make sure it's set on the team-api.18f.gov server when you're ready.
