### ISSUE TITLE
Formalize the team member schema

### ISSUE THREAD

**Issue by mtorres253** [18F/team_api#54]
In order for people to know what information to enter for each team member, and so that we can do validation against any input, there should be a formal team member schema.

Acceptance Criteria: Showing the defined schema can be the demo and showing a piece of data validated against it.

**Comment by mtorres253** [comment]
@catherinedevlin has some deep experience with Team API and may have some helpful input

**Comment by ccostino** [comment]
https://github.com/18F/team_api/pull/59 has been merged, so unless there's something else left to do with this issue, we can probably close it. :-)

**Comment by ertzeid** [comment]
Hm... should this include adding a check against the schema for team
members, as we do already with .about.yml files for projects? cc @mtorres.

**Comment by mTorres** [comment]
Sorry @ertzeid you definitely meant @mtorres253 not me :-)

**Comment by mtorres253** [comment]
Thanks @ertzeid I'll add a story for validation and we can talk more on Thurs

**Comment by ertzeid** [comment]
SGTM*. Closing this issue then.

* Sounds Good To Me (never know who knows that one)
